# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5a6591cc4634f4bcbb6ee5cbd8ed635b6dc51e3a4a08e5060d2bebca616efe2f3b2ec61dd420300e2544ea657c21b26a92811550368ca0ba58352e5226ebfc8

test:
  secret_key_base: ca267d260b05bf5edde90831d5d3788e280b2859e0fdb35f9b7f3a1d7813b65ebcbe214a2f73b574ce76f4dfe32cbe3658177ee7c4ea802606ad412b48f2e573

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
